GET http://localhost:5000/socialapp-foyez/us-central1/api/screams

###

GET http://localhost:5000/socialapp-foyez/us-central1/api/screams/oDEplM8gVB23m3K6FkNf

###

POST http://localhost:5000/socialapp-foyez/us-central1/api/screams/tO5wJ5reWTfCNiXMy6TD/comment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjVlOWVlOTdjODQwZjk3ZTAyNTM2ODhhM2I3ZTk0NDczZTUyOGE3YjUiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vc29jaWFsYXBwLWZveWV6IiwiYXVkIjoic29jaWFsYXBwLWZveWV6IiwiYXV0aF90aW1lIjoxNTg4MDcyODA3LCJ1c2VyX2lkIjoiVG1tYzl1b2M4aE1QeTdJUUw5MHQzZVdJdFlGMyIsInN1YiI6IlRtbWM5dW9jOGhNUHk3SVFMOTB0M2VXSXRZRjMiLCJpYXQiOjE1ODgwNzI4MDcsImV4cCI6MTU4ODA3NjQwNywiZW1haWwiOiJyYWZlaEBlbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsicmFmZWhAZW1haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.2wUGQaae0YywdAedyZZ7BI4QIvCjs0r5wx5Yq5haF4fXLs79tongTnDEpKw1F1DU1nnisJlCs6jNpvTvrMosg8wy4qNxmJXUoBl45j-6h0Aa48ZG4cYyf3RN6PaMxxl79RBCTEXrRBSdaSzAMtsIpWpCd81_g9-DPUhAx_Ng8ij6ntaP_BioQW7CR4vUawaAtw1V88onfpJxdIkjKafO15sb40EeVR9kbEUDfMYJOgn1goLfs9d1-p8AZa41hQDYqpmVgtJ08EGNs5XhZEqXdSn7y8HSEeJupgEvenD6fczJN9ruhi4lQK8HvtaMJGcc_im0IItqGyPQ6w8XQLxe1w

{
  "body": "comment 2"
}

###

GET http://localhost:5000/socialapp-foyez/us-central1/api/screams/oDEplM8gVB23m3K6FkNf/like
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjVlOWVlOTdjODQwZjk3ZTAyNTM2ODhhM2I3ZTk0NDczZTUyOGE3YjUiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vc29jaWFsYXBwLWZveWV6IiwiYXVkIjoic29jaWFsYXBwLWZveWV6IiwiYXV0aF90aW1lIjoxNTg4MDY2MTEyLCJ1c2VyX2lkIjoiVG1tYzl1b2M4aE1QeTdJUUw5MHQzZVdJdFlGMyIsInN1YiI6IlRtbWM5dW9jOGhNUHk3SVFMOTB0M2VXSXRZRjMiLCJpYXQiOjE1ODgwNjYxMTIsImV4cCI6MTU4ODA2OTcxMiwiZW1haWwiOiJyYWZlaEBlbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsicmFmZWhAZW1haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.2ssnPjZJIJDZvNrzKMwXdmOlc8cusq_GdIVk81E6AvHardvzb9QpfIlqag9I_M1ck8ECbrmtuvJw8cHXXxp8hIMWiHP9Hc9NZOuUHM5sIo2w8pOp_CHUphHCE7GjGuGUGJK7V--LzkUkl7pXAb_ZsLJqaetGQsJIPG7cBhK9zhYYnhqGfx2tm9CWQ-Z0q9tcGBI9EMhR_Mv31B20r5BTMHLfYi-pZE5vtnn0fdrHomjUxxF2RhuTn_MHVKmtb-e9Mhp_Ch-BCw08niUnzWMvBRlpJCSvDYScxltu8vF3JffwMMVViqaKm3BEcVBMbq1cg0X-koy5FJlxXZ7PtwB9Dg

###

GET http://localhost:5000/socialapp-foyez/us-central1/api/screams/oDEplM8gVB23m3K6FkNf/unlike
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjVlOWVlOTdjODQwZjk3ZTAyNTM2ODhhM2I3ZTk0NDczZTUyOGE3YjUiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vc29jaWFsYXBwLWZveWV6IiwiYXVkIjoic29jaWFsYXBwLWZveWV6IiwiYXV0aF90aW1lIjoxNTg4MDcyODA3LCJ1c2VyX2lkIjoiVG1tYzl1b2M4aE1QeTdJUUw5MHQzZVdJdFlGMyIsInN1YiI6IlRtbWM5dW9jOGhNUHk3SVFMOTB0M2VXSXRZRjMiLCJpYXQiOjE1ODgwNzI4MDcsImV4cCI6MTU4ODA3NjQwNywiZW1haWwiOiJyYWZlaEBlbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsicmFmZWhAZW1haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.2wUGQaae0YywdAedyZZ7BI4QIvCjs0r5wx5Yq5haF4fXLs79tongTnDEpKw1F1DU1nnisJlCs6jNpvTvrMosg8wy4qNxmJXUoBl45j-6h0Aa48ZG4cYyf3RN6PaMxxl79RBCTEXrRBSdaSzAMtsIpWpCd81_g9-DPUhAx_Ng8ij6ntaP_BioQW7CR4vUawaAtw1V88onfpJxdIkjKafO15sb40EeVR9kbEUDfMYJOgn1goLfs9d1-p8AZa41hQDYqpmVgtJ08EGNs5XhZEqXdSn7y8HSEeJupgEvenD6fczJN9ruhi4lQK8HvtaMJGcc_im0IItqGyPQ6w8XQLxe1w

###

DELETE http://localhost:5000/socialapp-foyez/us-central1/api/screams/oDEplM8gVB23m3K6FkNf
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjVlOWVlOTdjODQwZjk3ZTAyNTM2ODhhM2I3ZTk0NDczZTUyOGE3YjUiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vc29jaWFsYXBwLWZveWV6IiwiYXVkIjoic29jaWFsYXBwLWZveWV6IiwiYXV0aF90aW1lIjoxNTg4MDcyODA3LCJ1c2VyX2lkIjoiVG1tYzl1b2M4aE1QeTdJUUw5MHQzZVdJdFlGMyIsInN1YiI6IlRtbWM5dW9jOGhNUHk3SVFMOTB0M2VXSXRZRjMiLCJpYXQiOjE1ODgwNzI4MDcsImV4cCI6MTU4ODA3NjQwNywiZW1haWwiOiJyYWZlaEBlbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsicmFmZWhAZW1haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.2wUGQaae0YywdAedyZZ7BI4QIvCjs0r5wx5Yq5haF4fXLs79tongTnDEpKw1F1DU1nnisJlCs6jNpvTvrMosg8wy4qNxmJXUoBl45j-6h0Aa48ZG4cYyf3RN6PaMxxl79RBCTEXrRBSdaSzAMtsIpWpCd81_g9-DPUhAx_Ng8ij6ntaP_BioQW7CR4vUawaAtw1V88onfpJxdIkjKafO15sb40EeVR9kbEUDfMYJOgn1goLfs9d1-p8AZa41hQDYqpmVgtJ08EGNs5XhZEqXdSn7y8HSEeJupgEvenD6fczJN9ruhi4lQK8HvtaMJGcc_im0IItqGyPQ6w8XQLxe1w

###

POST http://localhost:5000/socialapp-foyez/us-central1/api/screams
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjVlOWVlOTdjODQwZjk3ZTAyNTM2ODhhM2I3ZTk0NDczZTUyOGE3YjUiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vc29jaWFsYXBwLWZveWV6IiwiYXVkIjoic29jaWFsYXBwLWZveWV6IiwiYXV0aF90aW1lIjoxNTg4MDY2MTEyLCJ1c2VyX2lkIjoiVG1tYzl1b2M4aE1QeTdJUUw5MHQzZVdJdFlGMyIsInN1YiI6IlRtbWM5dW9jOGhNUHk3SVFMOTB0M2VXSXRZRjMiLCJpYXQiOjE1ODgwNjYxMTIsImV4cCI6MTU4ODA2OTcxMiwiZW1haWwiOiJyYWZlaEBlbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsicmFmZWhAZW1haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.2ssnPjZJIJDZvNrzKMwXdmOlc8cusq_GdIVk81E6AvHardvzb9QpfIlqag9I_M1ck8ECbrmtuvJw8cHXXxp8hIMWiHP9Hc9NZOuUHM5sIo2w8pOp_CHUphHCE7GjGuGUGJK7V--LzkUkl7pXAb_ZsLJqaetGQsJIPG7cBhK9zhYYnhqGfx2tm9CWQ-Z0q9tcGBI9EMhR_Mv31B20r5BTMHLfYi-pZE5vtnn0fdrHomjUxxF2RhuTn_MHVKmtb-e9Mhp_Ch-BCw08niUnzWMvBRlpJCSvDYScxltu8vF3JffwMMVViqaKm3BEcVBMbq1cg0X-koy5FJlxXZ7PtwB9Dg

{
  "body": "Nice Scream",
  "username": "foyez"
}

###

POST http://localhost:5000/socialapp-foyez/us-central1/api/users
Content-Type: application/json

{
  "email": "rafeh@email.com",
  "username": "rafeh",
  "password": "testpass",
  "confirmPassword": "testpass"
}

###

POST http://localhost:5000/socialapp-foyez/us-central1/api/users/login
Content-Type: application/json

{
  "email": "rafeh@email.com",
  "password": "testpass"
}

###

PUT http://localhost:5000/socialapp-foyez/us-central1/api/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjVlOWVlOTdjODQwZjk3ZTAyNTM2ODhhM2I3ZTk0NDczZTUyOGE3YjUiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vc29jaWFsYXBwLWZveWV6IiwiYXVkIjoic29jaWFsYXBwLWZveWV6IiwiYXV0aF90aW1lIjoxNTg3NzEzNzc2LCJ1c2VyX2lkIjoiVG1tYzl1b2M4aE1QeTdJUUw5MHQzZVdJdFlGMyIsInN1YiI6IlRtbWM5dW9jOGhNUHk3SVFMOTB0M2VXSXRZRjMiLCJpYXQiOjE1ODc3MTM3NzYsImV4cCI6MTU4NzcxNzM3NiwiZW1haWwiOiJyYWZlaEBlbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsicmFmZWhAZW1haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.PCaolNMdV3cg3ChniPGI_3J2RBjfSQe-pC9i1oPwSCKGGXe2e87xj-yDd7QmW004Gt7xu6lReBvOiHcGrH4SbItoVogrv0MKRomCJcnyqN3dw79rANYYP_QPmd0AflNICZF2uloXe8B7HDi38Qfcx936HoPKAsKmusLspUyWoXAoFqrAtWozFOyn42hJ78eeD8WOGAXmGQ5aYj3nVudtj28uGxGbtah_p75YKZSg0Nnu4IeaCHYygQKm4iJicnBUPkLYtggHm9ncxQSsl3A3j9iZIwLMMTQuhIDvkp4xj65VjZ38eMA1dL0mzAPtrC4qkAAKaSAfXmoxeyeS6jZjiA

{
  "bio": "   Hello, I'm Rafeh.",
  "website": "user.com",
  "location": "Cumilla, BD"
}

###

GET http://localhost:5000/socialapp-foyez/us-central1/api/user
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjVlOWVlOTdjODQwZjk3ZTAyNTM2ODhhM2I3ZTk0NDczZTUyOGE3YjUiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vc29jaWFsYXBwLWZveWV6IiwiYXVkIjoic29jaWFsYXBwLWZveWV6IiwiYXV0aF90aW1lIjoxNTg3NzU3NzY0LCJ1c2VyX2lkIjoiVG1tYzl1b2M4aE1QeTdJUUw5MHQzZVdJdFlGMyIsInN1YiI6IlRtbWM5dW9jOGhNUHk3SVFMOTB0M2VXSXRZRjMiLCJpYXQiOjE1ODc3NTc3NjQsImV4cCI6MTU4Nzc2MTM2NCwiZW1haWwiOiJyYWZlaEBlbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsicmFmZWhAZW1haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.OF2n2e8ngvWntUA6Z05piiY2NJsieN7LEkLX5KPuMvhsnNtszyxxW-JeyrhTefQ5KZXtGICx3LRlnXtGo9loyyuXiNTCNsxxKUvKCvJ6H_uw42fhSjUvBep4tfIDaFNg_Gm2ffFtkqHrfOuQCIh7CthQOcZ5vQcDFOiFeTDwtGJkTP3ATsjYFpqYX25zI0rIpZPKkqduASnTxvgd48HS71TX05kLNbzVd6D5zfV0fWTepqJjP2N4zdqQhtp6FPUUHkbpzbJnyLERS0zXzFQzrDun7wuW_Gmjep-xd-LhOQEwt0HJFgTX6z5GZAdzsNNhTudCDQ9T45GCsNdlqciK_A

###

POST http://localhost:5000/socialapp-foyez/us-central1/api/user/image
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjVlOWVlOTdjODQwZjk3ZTAyNTM2ODhhM2I3ZTk0NDczZTUyOGE3YjUiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vc29jaWFsYXBwLWZveWV6IiwiYXVkIjoic29jaWFsYXBwLWZveWV6IiwiYXV0aF90aW1lIjoxNTg3NzA5MDA3LCJ1c2VyX2lkIjoiRUtpM0lLcHd2ellQOG5mQkxOcW03WDR0WHFHMiIsInN1YiI6IkVLaTNJS3B3dnpZUDhuZkJMTnFtN1g0dFhxRzIiLCJpYXQiOjE1ODc3MDkwMDcsImV4cCI6MTU4NzcxMjYwNywiZW1haWwiOiJmb3llekBlbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiZm95ZXpAZW1haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.Mkt7NrFasSmVGnfbiSZKzD0tYaOy50usBuGguGH07zdyRi_aPrxsuIonRFzK2Ti--VvXFlKS3XxkyzptjyetQNYa8vym2ztdXDgJGOZUxyUtNaXfT_Nd2GU2jt3Yk4fgpoK4U2jZ9KiL2r5zflITxnWFm8EMIYbtQiORnd-ifP2EGfMbt4wLv4FYsLMnkgUTNcpgQCcnXAiBOxU2toGns98zXC5f86ykcIE12Ad7qSbnVr2CRv3MCp4h6MgHSB53Z13P0_uHzDgiRWc94DO9Y4P_AvAP90VeBpRQ45cnPpofj3lZbP7kvRbCgleGkskSiws_lfld0yrOvtSMbcg_Mw