GET http://localhost:5000/socialapp-foyez/us-central1/api/screams

###

POST http://localhost:5000/socialapp-foyez/us-central1/api/screams
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjBiYWJiMjI0NDBkYTAzMmM1ZDAwNDJjZGFhOWQyODVjZjhkMjAyYzQiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vc29jaWFsYXBwLWZveWV6IiwiYXVkIjoic29jaWFsYXBwLWZveWV6IiwiYXV0aF90aW1lIjoxNTg3NDgwNzg4LCJ1c2VyX2lkIjoiRUtpM0lLcHd2ellQOG5mQkxOcW03WDR0WHFHMiIsInN1YiI6IkVLaTNJS3B3dnpZUDhuZkJMTnFtN1g0dFhxRzIiLCJpYXQiOjE1ODc0ODA3ODgsImV4cCI6MTU4NzQ4NDM4OCwiZW1haWwiOiJmb3llekBlbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiZm95ZXpAZW1haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.Qo1zkpBZ-WDIdOVGdJQdq6r485-hETtBnX-j_OVQSq4zV_nt1VV1yN96QlkIh0T27xQFX8nFS5ZwG5X_TOOLKEw-3Dzk6csqv1KloyNxAV42OiBgBd-4MpL_1ylLoiITVOasdNeXCcQJumuZdXFB43SvKKHgzNC7D4TqJ4U_ZK4qN0Pi5LQzC_mB7zx-QBu2MCnb2s4PXOyUBk70rX6CvkI0F3EOzboePLx3yxzCJPTBFqJqn_sS4GyZW7ZPeb6CJG7O_vkhqUkpcFiFF2Ut-Bqg4cOc4_--yqBSdCQD2cyJP6MrXJfcqJYFOAJ-sbejdXQv9_vCMSUB7sMH7Glpzg

{
  "body": "new scream 2",
  "username": "new2"
}

###

POST http://localhost:5000/socialapp-foyez/us-central1/api/users
Content-Type: application/json

{
  "email": "foyez@email.com",
  "username": "foyez",
  "password": "testpass",
  "confirmPassword": "testpass"
}

###

POST http://localhost:5000/socialapp-foyez/us-central1/api/users/login
Content-Type: application/json

{
  "email": "foyez@email.com",
  "password": "testpass"
}